"""empty message

Revision ID: 0eb8ae5a1708
Revises: 071d3bec5dcc
Create Date: 2017-03-30 13:18:15.846876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eb8ae5a1708'
down_revision = '071d3bec5dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('registerAddress', sa.String(), nullable=True),
    sa.Column('registerTime', sa.String(), nullable=True),
    sa.Column('divermMileage', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_name', sa.String(), nullable=True),
    sa.Column('admin_code', sa.String(), nullable=True),
    sa.Column('initial', sa.String(), nullable=True),
    sa.Column('prov_id', sa.String(), nullable=True),
    sa.Column('prov_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city')
    op.drop_table('cars')
    # ### end Alembic commands ###
