"""empty message

Revision ID: 141f24d05d0e
Revises: 
Create Date: 2017-03-30 19:04:37.545981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '141f24d05d0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('registerAddress', sa.String(), nullable=True),
    sa.Column('registerTime', sa.String(), nullable=True),
    sa.Column('divermMileage', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(), nullable=True),
    sa.Column('initial', sa.String(), nullable=True),
    sa.Column('update_time', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maker_type', sa.String(), nullable=True),
    sa.Column('series_name', sa.String(), nullable=True),
    sa.Column('series_group_name', sa.String(), nullable=True),
    sa.Column('update_time', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_name', sa.String(), nullable=True),
    sa.Column('admin_code', sa.String(), nullable=True),
    sa.Column('initial', sa.String(), nullable=True),
    sa.Column('prov_id', sa.String(), nullable=True),
    sa.Column('prov_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('cars', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('city')
    op.drop_table('car_series')
    op.drop_table('car_brand')
    op.drop_table('car')
    # ### end Alembic commands ###
