"""empty message

Revision ID: d91ea35ff5cf
Revises: ed930ec12d3d
Create Date: 2017-03-30 14:36:36.023967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91ea35ff5cf'
down_revision = 'ed930ec12d3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carBrand', sa.Column('brand_id', sa.Integer(), nullable=False))
    op.drop_column('carBrand', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carBrand', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_column('carBrand', 'brand_id')
    # ### end Alembic commands ###
