"""empty message

Revision ID: ed930ec12d3d
Revises: 0eb8ae5a1708
Create Date: 2017-03-30 14:35:08.179512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed930ec12d3d'
down_revision = '0eb8ae5a1708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carBrand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(), nullable=True),
    sa.Column('initial', sa.String(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carSeries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_name', sa.String(), nullable=True),
    sa.Column('series_group_name', sa.String(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carSeries')
    op.drop_table('carBrand')
    # ### end Alembic commands ###
